### ISSUE TITLE
[Umbrella] Plan to release 1.0.0

### ISSUE THREAD

**Issue by dancerphil** [regionjs/region-core#1]
## infrastructure

- [x] Typescript

  Done #2 , strict type inspection will be added during long-term development

- [x] enable Typescript strict

- [x] export d.ts

- [x] ~~rollup (Typescript is enough for now)~~

- [x] ~~try [reskript](https://www.npmjs.com/package/reskript)  (Typescript is enough for now)~~

## flexible boundary of redux

- [x] remove dependencies of react-redux

- [x] each region create its own store (prevent unnecessary rendering)

## normalize (optional)

- [ ] try [query-shape](https://www.npmjs.com/package/query-shape)

- [ ] maybe a hook help developer pick and memoize entities

## fp (optional)

- [ ] optimize setFp & loadFp

- [x] discuss whether it is called setBy & loadBy (it is now)

## Surrounding Package (optional)

- [ ] update  region-form to support useProps

- [ ] release region-request(or as region-restful)
