### ISSUE TITLE
[Umbrella] Plan to release 9.0.0

### ISSUE THREAD

**Issue by dancerphil** [regionjs/region-core#11]
## Normalize (optional)

- [x] ~~try [query-shape](https://www.npmjs.com/package/query-shape)~~

- [x] maybe a hook help developer pick and memoize entities __note: as id__

## TS (optional)

- [x] develop a pattern to write in form of wrapFunction

## APIs

- [x] ~~unstable_effect #10~~ __note: removed__

- [x] load with id

- [x] set with function `region.set(count => count + 1)` #16

- [x] rename apis to `createRegion`, `createLocalStorageRegion`

- [x] another callback like format called reducer

## Deps

- [x] reimplement `redux`

## Docs

- [x] rewrite document entirely

## Surrounding Packages

- [x] ~~extract region-throttle~~__note: abandoned__

- [x] release region-localStorage __note: as createLocalStorageRegion__

- [x] release region-entity __note: as createRegion__

- [x] ~~extract region-react (maybe after 9.0.0)~~__note: abandoned__

**Comment by dancerphil** [comment]
9.0.0 will release soon after internal test.
