### ISSUE TITLE
[Umbrella] Plan to release 10.0.0

### ISSUE THREAD

**Issue by dancerphil** [regionjs/region-core#19]
## Normalize with loadBy

- [x] loadBy with id as a selector

- [x] publish normalize practice(as swr)

## TypeScript

- [x] generics for createRegion

## Current Mode

- [ ] useSuspense and other current mode api
